### ISSUE TITLE
The cron from tour operator plugin runs even when the addon is deactivated

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Tour-operators-addon#34]
I have Tour operators addon deactivated yet I can see that the cron from the addon is running.

http://screencast.com/t/GWYPkCq8B7fp

**Comment by apeksha10** [comment]
With the latest git copy, I have checked that the cron is not running if addon is deactivate 

So I am not able to replicate the above issue

Hence closed this issue
