### ISSUE TITLE
All products assigned to tour operator are not displayed together

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Tour-operators-addon#35]
I have 8 products that are assigned to a tour operator 'tour'. But when the tour operator logs in, the Products page is showing only 1 product. To see all the 8 products, he will need to navigate through all the pages to see his products.

http://screencast.com/t/fVHWJ95vUJZ1

**Comment by apeksha10** [comment]
This is a very old issue.
None of the clients has come up with this issue 

Hence I have closed this issue
