### ISSUE TITLE
All orders placed for products assigned to tour operator are not displayed together

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Tour-operators-addon#36]
I have multiple orders placed for products that are assigned to a tour operator 'tour'. But when the tour operator logs in, the WooCommerce> Orders page is showing only 1 order on the 1st page. To see all the orders, he will need to navigate through all the pages to see his orders.

http://screencast.com/t/3InmcXQNqd

**Comment by apeksha10** [comment]
This is a very old issue.
None of the clients has come up with this issue 

Hence I have closed this issue
