### ISSUE TITLE
HIGH PRIORITY - The pagination is based on all records for admin and not based on the tour operators records on View Bookings Page.

### ISSUE THREAD

**Issue by moxajogani** [TycheSoftwares/Tour-operators-addon#38]
The pagination is based on all records for admin and not based on the tour operators records on View Bookings Page. http://screencast.com/t/bQWsMjfkpV9

It displays fine in the All, Bookings from Today Onwards and other links.

**Comment by apeksha10** [comment]
This is a very old issue.
None of the clients has come up with this issue 

Hence I have closed this issue
