### ISSUE TITLE
Getting Notices when the order received by the tour operator when order is marked completed

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Tour-operators-addon#42]
When an order is marked completed and 'Send Notification emails to Tour operators' setting is enabled under Addon settings tab, I am getting notices in the email received by the tour operator.

http://screencast.com/t/klHz69fHsi

**Comment by apeksha10** [comment]
None of the clients has come up with this issue 
We can re-open if needed 

Currently, I have closed this issue
