### ISSUE TITLE
Other tour operator should not be displayed while Tour operator creates a new product and assigns the tour operator

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Tour-operators-addon#57]
When a Tour operator creates a new product and assigns the tour operator, apart from his/her tour operator username, no other tour operator should be displayed in the tour operator drop down on the Edit product page.

This also should be the case while editing an existing product assigned to the tour operator.

**Comment by apeksha10** [comment]
This is a very old issue
None of the clients has come up with this issue

Hence I have closed this issue.
