### ISSUE TITLE
Custom fields are not displaying in the Tour operator's account

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Tour-operators-addon#68]
Custom fields which are added using the plugin "Advanced Custom Fields PRO" are not displaying in the Tour operator's account. Admin can see this custom fields at the backend of the product/page.

Client issue link: https://www.tychesoftwares.com/forums/topic/unable-to-view-custom-fields-in-the-profile-or-product-page/

**Comment by apeksha10** [comment]
This is a very old issue.

Hence I have closed this issue
