### ISSUE TITLE
Replace old UI screenshots in the documentation.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Tour-operators-addon#71]
The documentation for this addon has old UI screenshots in it, we need to replace them with screenshots with the current UI.

https://www.tychesoftwares.com/docs/docs/booking-appointment-plugin-for-woocommerce/add-ons/tour-operators-addon/

**Comment by tedioustanisha** [comment]
@geogirish the link for documentation does not open. pls guide

**Comment by ashokrane** [comment]
@upenkapse @priyanka-tychesoftwares  I am closing this issue. We are not selling the Tour operators addon any longer. The current list of addons is here: https://www.tychesoftwares.com/docs/woocommerce-booking-appointment-plugin/booking-addons/ .
